{"name": "test_http[test_data3]", "status": "broken", "statusDetails": {"message": "NameError: name 'UserLog' is not defined", "trace": "self = <test_case.test_login_pytest.TestHttp object at 0x0A21DFF0>\ntest_data = {'ID': 4, 'data': '{\"username\":\"auto\",\"password\":\"1sdfsdfsdf\"}', 'exp': 1, 'header': '{\"User-Agent\":\"Mozilla/5.0(Windo...harm-df2c00ac=f0bfa5fa-bf37-4140-9195-bc4a322fc2a1; goSessionid=j5wML4oBLTKoE18Y9aOkEN6IOYNK0vPEkYIorE-MZz8%3D\"}', ...}\n\n    @pytest.mark.parametrize(\"test_data\", test_data)\n    def test_http(self, test_data):\n    \n>       UserLog().info('/*开始->ID:{0},标题:{1}*/'.format(test_data['ID'],test_data['title']))\nE       NameError: name 'UserLog' is not defined\n\ntest_case\\test_login_pytest.py:21: NameError"}, "parameters": [{"name": "test_data", "value": "{'ID': 4, 'title': '密码错误登录', 'mode': 'login', 'method': 'post', 'url': 'http://localhost/api/mgr/loginReq', 'header': '{\"User-Agent\":\"Mozilla/5.0(Windows NT 6.1)\",\"Content-Type\":\"application/x-www-form-urlencoded; charset=UTF-8\",\"Cookie\":\"Pycharm-df2c00ac=f0bfa5fa-bf37-4140-9195-bc4a322fc2a1; goSessionid=j5wML4oBLTKoE18Y9aOkEN6IOYNK0vPEkYIorE-MZz8%3D\"}', 'data': '{\"username\":\"auto\",\"password\":\"1sdfsdfsdf\"}', 'exp': 1, 'res': \"{'retcode': 1, 'reason': '用户或者密码错误'}\", 'testresult': 'Pass', 'sheet_name': 'login'}"}], "start": 1596722817772, "stop": 1596722817772, "uuid": "2e656774-0048-4450-a7bf-33ad8c1109a1", "historyId": "6378670de4b090548e337ff65751eeb8", "testCaseId": "1c58897f264d102e09670d4cf5c32252", "fullName": "test_case.test_login_pytest.TestHttp#test_http", "labels": [{"name": "tag", "value": "usefixtures"}, {"name": "parentSuite", "value": "test_case"}, {"name": "suite", "value": "test_login_pytest"}, {"name": "subSuite", "value": "TestHttp"}, {"name": "host", "value": "PC-20181102DJCG"}, {"name": "thread", "value": "9124-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_case.test_login_pytest"}]}